In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("(1) graduate employment survey modified.csv")
df1 = pd.read_csv("(2) graduate employment survey modified .csv")

# MERGE ON KEY
df_merged = df.merge(df1, on="Key")
# REMOVE UNNAMED COLUMNS
df_clean = df_merged.loc[:,
    ~df_merged.columns.str.contains('Unnamed', case=False, na=False)
]
df_cleaned = df_clean.loc[:, ~df_clean.T.duplicated()]
print(df_cleaned.info())
# SAVE TO CSV
df_cleaned.to_csv('merged.csv', index=False)

# COPY THE SAVED CSV
df_copy = df_cleaned.copy()
df_copy = df_copy.dropna()
print(df_copy.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5135 entries, 0 to 5134
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   year                       5135 non-null   object
 1   university                 5135 non-null   object
 2   school                     5135 non-null   object
 3   degree                     5135 non-null   object
 4   Key                        5135 non-null   int64
 5   employment_rate_overall    5027 non-null   object
 6   employment_rate_ft_perm    5027 non-null   object
 7   basic_monthly_mean         5027 non-null   object
 8   basic_monthly_median       5027 non-null   object
 9   gross_monthly_mean         5027 non-null   object
 10  gross_monthly_median       5027 non-null   object
 11  gross_mthly_25_percentile  5027 non-null   object
 12  gross_mthly_75_percentile  5027 non-null   object
dtypes: int64(1), object(12)
memory usage: 521.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
Index: 5027 entries, 0 to 5134
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   year                       5027 non-null   object
 1   university                 5027 non-null   object
 2   school                     5027 non-null   object
 3   degree                     5027 non-null   object
 4   Key                        5027 non-null   int64
 5   employment_rate_overall    5027 non-null   object
 6   employment_rate_ft_perm    5027 non-null   object
 7   basic_monthly_mean         5027 non-null   object
 8   basic_monthly_median       5027 non-null   object
 9   gross_monthly_mean         5027 non-null   object
 10  gross_monthly_median       5027 non-null   object
 11  gross_mthly_25_percentile  5027 non-null   object
 12  gross_mthly_75_percentile  5027 non-null   object
dtypes: int64(1), object(12)
memory usage: 549.8+ KB
None

# PDAS CA2
# Do graduates prioritise salary or company stability when choosing jobs in Singapore?
 This study investigates whether graduates in Singapore prioritise higher salaries or company stability and culture when choosing jobs. As company culture is not directly measurable through employment datasets, employment stability indicators such as full-time permanent employment rates are used as a proxy for organisational culture. By analysing salary and stability trends across degrees and over time, this study aims to identify trade-offs between pay, job security, and culture-related employment outcomes

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv(r'C:\Users\JunHao\Downloads\PDAS_CA2\CA2 Datasets\CA2 Datasets\CA2 Datasets\(1) graduate employment survey modified.csv')
df1 = pd.read_csv(r"C:\Users\JunHao\Downloads\PDAS_CA2\CA2 Datasets\CA2 Datasets\CA2 Datasets\(2) graduate employment survey modified .csv")
print("DF HERE")
df.info()
print("DF1 HERE")
df1.info()

DF HERE
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5135 entries, 0 to 5134
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        5135 non-null   object
 1   university  5135 non-null   object
 2   school      5135 non-null   object
 3   degree      5135 non-null   object
 4   Key         5135 non-null   int64
dtypes: int64(1), object(4)
memory usage: 200.7+ KB
DF1 HERE
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5135 entries, 0 to 5134
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   employment_rate_overall      5027 non-null   object
 1   employment_rate_ft_perm      5027 non-null   object
 2   basic_monthly_mean           5027 non-null   object
 3   basic_monthly_median         5027 non-null   object
 4   gross_monthly_mean           5027 non-null   object
 5   gross_monthly_median         5027 non-null   object
 6   gross_mthly_25_percentile    5027 non-null   object
 7   gross_mthly_75_percentile    5027 non-null   object
 8   gross_monthly_mean.1         5027 non-null   object
 9   gross_monthly_median.1       5027 non-null   object
 10  gross_mthly_25_percentile.1  5027 non-null   object
 11  gross_mthly_75_percentile.1  5027 non-null   object
 12  Unnamed: 12                  0 non-null      float64
 13  Unnamed: 13                  0 non-null      float64
 14  Unnamed: 14                  0 non-null      float64
 15  Unnamed: 15                  0 non-null      float64
 16  Unnamed: 16                  0 non-null      float64
 17  Unnamed: 17                  0 non-null      float64
 18  Unnamed: 18                  0 non-null      float64
 19  Unnamed: 19                  0 non-null      float64
 20  Unnamed: 20                  0 non-null      float64
 21  Unnamed: 21                  0 non-null      float64
 22  Unnamed: 22                  0 non-null      float64
 23  Unnamed: 23                  0 non-null      float64
 24  Unnamed: 24                  0 non-null      float64
 25  Unnamed: 25                  0 non-null      float64
 26  Unnamed: 26                  0 non-null      float64
 27  Unnamed: 27                  0 non-null      float64
 28  Unnamed: 28                  0 non-null      float64
 29  Unnamed: 29                  0 non-null      float64
 30  Unnamed: 30                  0 non-null      float64
 31  Unnamed: 31                  0 non-null      float64
 32  Unnamed: 32                  0 non-null      float64
 33  Unnamed: 33                  0 non-null      float64
 34  Unnamed: 34                  0 non-null      float64
 35  Unnamed: 35                  0 non-null      float64
 36  Unnamed: 36                  0 non-null      float64
 37  Unnamed: 37                  0 non-null      float64
 38  Unnamed: 38                  0 non-null      float64
 39  Unnamed: 39                  0 non-null      float64
 40  Unnamed: 40                  0 non-null      float64
 41  Unnamed: 41                  0 non-null      float64
 42  Unnamed: 42                  0 non-null      float64
 43  Unnamed: 43                  0 non-null      float64
 44  Unnamed: 44                  0 non-null      float64
 45  Unnamed: 45                  0 non-null      float64
 46  Unnamed: 46                  0 non-null      float64
 47  Key                          5135 non-null   int64
dtypes: float64(35), int64(1), object(12)
memory usage: 1.9+ MB

In [2]:
df.head(5)

,year,university,school,degree,Key
0,2013,Nanyang Technological University,College of Business (Nanyang Business School),Accountancy and Business,1
1,2013,Nanyang Technological University,College of Business (Nanyang Business School),Accountancy (3-yr direct Honours Programme),2
2,2013,Nanyang Technological University,College of Business (Nanyang Business School),Business (3-yr direct Honours Programme),3
3,2013,Nanyang Technological University,College of Business (Nanyang Business School),Business and Computing,4
4,2013,Nanyang Technological University,College of Engineering,Aerospace Engineering,5

In [3]:
df1.head(5)

,employment_rate_overall,employment_rate_ft_perm,basic_monthly_mean,basic_monthly_median,gross_monthly_mean,gross_monthly_median,gross_mthly_25_percentile,gross_mthly_75_percentile,gross_monthly_mean.1,gross_monthly_median.1,...,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Key
0,97.4,96.1,3701,3200,3727,3350,2900,4000,3727,3350,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,97.1,95.7,2850,2700,2938,2700,2700,2900,2938,2700,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
2,90.9,85.7,3053,3000,3214,3000,2700,3500,3214,3000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
3,87.5,87.5,3557,3400,3615,3400,3000,4100,3615,3400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
4,95.3,95.3,3494,3500,3536,3500,3100,3816,3536,3500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5

In [4]:
df_merged = df.merge(df1, on="Key")
df_merged.head(5)

,year,university,school,degree,Key,employment_rate_overall,employment_rate_ft_perm,basic_monthly_mean,basic_monthly_median,gross_monthly_mean,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
0,2013,Nanyang Technological University,College of Business (Nanyang Business School),Accountancy and Business,1,97.4,96.1,3701,3200,3727,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2013,Nanyang Technological University,College of Business (Nanyang Business School),Accountancy (3-yr direct Honours Programme),2,97.1,95.7,2850,2700,2938,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2013,Nanyang Technological University,College of Business (Nanyang Business School),Business (3-yr direct Honours Programme),3,90.9,85.7,3053,3000,3214,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2013,Nanyang Technological University,College of Business (Nanyang Business School),Business and Computing,4,87.5,87.5,3557,3400,3615,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013,Nanyang Technological University,College of Engineering,Aerospace Engineering,5,95.3,95.3,3494,3500,3536,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df_clean = df_merged.loc[:,
    ~df_merged.columns.str.contains('Unnamed', case=False, na=False)
]
df_cleaned = df_clean.loc[:,
    ~df_clean.columns.str.contains('.1', case=False, na=False)
]

In [22]:
# Check missing values
print(df_cleaned.isna().sum())
# Save to CSV
df_cleaned.to_csv('merged.csv', index=False)

year                           0
university                     0
school                         0
degree                         0
Key                            0
employment_rate_overall      108
employment_rate_ft_perm      108
basic_monthly_mean           108
basic_monthly_median         108
gross_monthly_mean           108
gross_monthly_median         108
gross_mthly_25_percentile    108
gross_mthly_75_percentile    108
dtype: int64

In [23]:
df_copy = df_cleaned.copy()
df_copy.info()
df_copy.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5135 entries, 0 to 5134
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   year                       5135 non-null   object
 1   university                 5135 non-null   object
 2   school                     5135 non-null   object
 3   degree                     5135 non-null   object
 4   Key                        5135 non-null   int64
 5   employment_rate_overall    5027 non-null   object
 6   employment_rate_ft_perm    5027 non-null   object
 7   basic_monthly_mean         5027 non-null   object
 8   basic_monthly_median       5027 non-null   object
 9   gross_monthly_mean         5027 non-null   object
 10  gross_monthly_median       5027 non-null   object
 11  gross_mthly_25_percentile  5027 non-null   object
 12  gross_mthly_75_percentile  5027 non-null   object
dtypes: int64(1), object(12)
memory usage: 521.7+ KB

,year,university,school,degree,Key,employment_rate_overall,employment_rate_ft_perm,basic_monthly_mean,basic_monthly_median,gross_monthly_mean,gross_monthly_median,gross_mthly_25_percentile,gross_mthly_75_percentile
0,2013,Nanyang Technological University,College of Business (Nanyang Business School),Accountancy and Business,1,97.4,96.1,3701,3200,3727,3350,2900,4000
1,2013,Nanyang Technological University,College of Business (Nanyang Business School),Accountancy (3-yr direct Honours Programme),2,97.1,95.7,2850,2700,2938,2700,2700,2900
2,2013,Nanyang Technological University,College of Business (Nanyang Business School),Business (3-yr direct Honours Programme),3,90.9,85.7,3053,3000,3214,3000,2700,3500
3,2013,Nanyang Technological University,College of Business (Nanyang Business School),Business and Computing,4,87.5,87.5,3557,3400,3615,3400,3000,4100
4,2013,Nanyang Technological University,College of Engineering,Aerospace Engineering,5,95.3,95.3,3494,3500,3536,3500,3100,3816